spring.application.name=learning
isOnline = true
connection.enabled = noSql
user_name = default
password = default
#spring.profiles.active= qa,dev
spring.web.error.include-message=always

spring.datasource.url=jdbc:h2:mem:userDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
